name: hs_cil
channels:
  - conda-forge
  - ccpi
  - https://software.repos.intel.com/python/conda
dependencies:
  - astra-toolbox
  - ccpi-regulariser
  - cil
  - exspy
  - git
  - hyperspy-base>=2.0
  - hyperspy-gui-ipywidgets>=2.0
  # on linux, latest version seems to have binary incompatibility issue
  # https://github.com/TomographicImaging/CIL/issues/1970
  - ipp 2021.12.1  # [linux]
  - ipympl
  - libblas=*=*mkl
  - numba
  - numexpr
  - pip
  - pystackreg
  - scikit-learn
  - scikit-image
  - tomophantom
  # astra-toolbox requirement conflict
  # https://github.com/usnistgov/etspy/issues/14
  #- pip:
  #  # until etspy is available on pypi.org
  #  - git+https://github.com/usnistgov/etspy
